function [flistNames stimNames]=get_standard_stimulus_names

flistNames = {...
    'flist_white_noise_checkerboard',...
    'flist_movie_original', ...
    'flist_movie_static_surr_median',...
    'flist_movie_dynamic_surr_median_each_frame',...
    'flist_movie_dynamic_surr_median_each_frame_shuffled',... %5
    'flist_movie_pix_surr_10_percent',...
    'flist_movie_pix_surr_50_percent',...
    'flist_movie_pix_surr_90_percent',...
    'flist_noise_movie',...
    'flist_noise_movie_varying_contrast',...%10
    'flist_drifting_half_sine_wave_ON',...
    'flist_drifting_half_sine_wave_OFF',...
    };

stimNames = {...
    'White_Noise',...
    'Movie_Original', ...
    'Movie_Static_Surr_Median',...
    'Movie_Dynamic_Surr_Median_Each_Frame',...
    'Movie_Dynamic_Surr_Median_Each_Frame_Shuffled',...%5
    'Movie_Pix_Surr_10_Percent',...
    'Movie_Pix_Surr_50_Percent',...
    'Movie_Pix_Surr_90_Percent',...
    'Noise_Movie',...
    'Noise_Movie_Varying_Contrast',...%10
    'Drifting_Half_Sine_Wave_ON',...
    'Drifting_Half_Sine_Wave_OFF',...
    };


end